### ISSUE TITLE
request: use traditional node style callbacks

### ISSUE THREAD

**Issue by cdaringe** [evantahler/browser_fingerprint#9]
# problem statement

- the bfp callback has the signature `function (hash) { ... }` vs the more widely known and conventional `function (err, hash, ...) { ... }`

this means that error handling cannot be a thing and that promisification doesn't work through the normal venues

**Comment by evantahler** [comment]
👍 

The new browser_fingerprint@0.1.0 has the callback style corrected

**Comment by evantahler** [comment]
https://github.com/evantahler/browser_fingerprint/commit/d386bfcde648244c48aef5768ef3fcdc6c47bae5

**Comment by cdaringe** [comment]
Awwwww yeya!  Standard baby!
